version: "3.4"

services:
  app:
    build: app
    image: app
    restart: "no"
    volumes:
      - ./app/:/app
      - ./app-cache/:/app-cache
    ports:
      - 7777:7777
    depends_on:
      - database
      - flyway
    env_file:
      - project.env

  database:
    container_name: database-server-two
    image: postgres:14.1
    restart: "no"
    env_file:
        - project.env

  flyway:
    image: flyway/flyway:9.11.0-alpine
    depends_on:
      - database
    volumes:
      - .:/flyway/sql
    command: -connectRetries=60 -baselineOnMigrate=true migrate
    env_file:
      - project.env

  e2e-playwright:
    # entrypoint: "/bin/true" # Prevent startup on docker-compose up
    entrypoint: /bin/bash -c "npm install && npx playwright install && npx playwright test"
    build: e2e-playwright
    image: mcr.microsoft.com/playwright:v1.47.2-focal
    network_mode: host
    depends_on:
      - app
    profiles:
      - test
    volumes:
      - ./e2e-playwright/tests:/e2e-playwright/tests